### ISSUE TITLE
Proper UI5 Theming Solution and CSS style var handling

### ISSUE THREAD

**Issue by maltenorstroem** [eclipse/eclipsefuro-web#1]
To avoid a chaotic css style var handling and to easy manage all the different themes, we need a solution to organise all the CSS stylevars in a named theme.

There are solutions from SAP but we have to think over this concepts.

 https://sap.github.io/ui5-webcomponents/playground/docs/configuration/
 https://sap.github.io/ui5-webcomponents/playground/docs/customtheming/
 

Existing style vars in components should be reviewed and adjusted. E.g. --primary, --on-primary only in Google Material Design System packages.

The goal is to provide two separated style var concepts. One for Google Material and one for SAP Fiori (@furo/ui5)

**Comment by veith** [comment]
With the 2.0 release we just have to implement the UI5 styles properly and get rid of the furo style vars.

**Comment by veith** [comment]
@maltenorstroem i think this issue belongs to https://github.com/theNorstroem/furo-ui5/issues.

Only the @furo/layout components have style vars, and they are commented in the documentation (like `--furo-horizontal-flex-space`)
