### ISSUE TITLE
<furo-data-number-input> with step="0.01"

### ISSUE THREAD

**Issue by MarcOmlin** [eclipse/eclipsefuro-web#19]
Hello Team

**Describe the bug**
I use <furo-data-number-input> with step="0.01" defined in my specs. Datatype is float.
I get some wrong error-messages unter my input-field when i enter for example 2.2
but 2.1 is working properly. I think there is a problem with the floating numbertype and im not sure how to fix this problem.

Do you have the same p problems in your webapps or maybe use <furo-data-number-input> only for int-types?

How can i solve this problem?

**To Reproduce**
1. Create a <furo-data-number-input> filed 
2. Add step="0.01"
3. Use Arrow-Up to increase the value.
4. Now you should see some error messages right under the input-field. 

**Expected behavior**
When i use a floating type and define a step on this <furo-data-numer-input>-filed i expect the field to be validated propperly or maybe to use the step option without any validation-messages. 

**Screenshots**

Input-Field with value 2.1 (no error)
<img width="660" alt="Input-Field 2 1" src="https://user-images.githubusercontent.com/42028916/129009736-01f5cb56-2436-4fb7-8989-771c3961acea.png">

Input-Field with value 2.2 (with error)
<img width="660" alt="Input-Field 2 2" src="https://user-images.githubusercontent.com/42028916/129009761-929f2aba-de2c-492b-9c44-bc3e58de83e9.png">

Spec-definition:
<img width="660" alt="Spec-definition" src="https://user-images.githubusercontent.com/42028916/129009794-b4635447-0cc7-47de-9926-ac008eb5949a.png">

Input-field definition
<img width="972" alt="Input-Field definition" src="https://user-images.githubusercontent.com/42028916/129009884-f5ad6d3d-2aff-4439-b695-1b0719960ca0.png">

Webapp package.json
<img width="972" alt="import package" src="https://user-images.githubusercontent.com/42028916/129009895-74858334-7ca1-45a6-b0bd-296ed6f0d657.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina Version 10.15.7
 - Chrome
 - Version (Google Chrome ist auf dem neuesten Stand)
Version 92.0.4515.131 (Offizieller Build) (x86_64)

**Additional context**
I use the npm import
  "dependencies": {
    "@furo/collection": "^1.3.82",
    "@furo/ui-builder": "^1.7.4",
    "lit-element": "^2.4.0"
  }

**Comment by maltenorstroem** [comment]
We will have to do more tests. The data type used is FLOAT. Float can not calculate modulo properly on fractions. This is the reason why the validator reports an error.

**Comment by veith** [comment]
We will make a decimal type for the baseTypes in near future with all the corresponding input and renderer elements. 

Quick solution for you at the moment is:
- remove the step from the spec
- add the step on the furo-data-number-input component
