### ISSUE TITLE
furo-type-renderer.js 

### ISSUE THREAD

**Issue by MarcOmlin** [eclipse/eclipsefuro-web#43]
Bug-Report with a suggestion to implement for 'eclipsefuro-web/packages/furo-data-ui/src/furo-type-renderer.js'

``**Describe the bug**
Elements do not disappear when used inside a template / flow-repeat.

**To Reproduce**
I created my own type-renderer based on yours and had some problems when using the typerenderer inside a template.
When the ƒ-inject-items was triggered additional fields where displayed because the old ones where not removed.

**Expected behavior**
I would recommend to add a disconnectedCallback() then the old fields are removed from the templates.

Sample-Code:

```
disconnectedCallback() {
   super.disconnectedCallback();
   if (this.defaultElement) {
      this.defaultElement.remove();
   }
}
```

**Comment by veith** [comment]
fixed in v2
