### ISSUE TITLE
Document the available slots

### ISSUE THREAD

**Issue by maltenorstroem** [eclipse/eclipsefuro-web#7]
We had no possibility to document the slots of a component.
The analyzers can handle them now and the custom-elements-manifest have them too.
 

* @slot - This is an unnamed slot (the default slot)
* @slot start - This is a slot named "start".
* @slot end

**Comment by veith** [comment]
Please also define what you can put in the slot.
Like:

```
/**
 * ....
 * @slot {HTMLElement} icon - A icon to be displayed in the input.
 * @slot {HTMLElement [0..n]} items - Put your form items here
 * /
```
